[twitch] 
login_name = 'your_bot_name'
channel_name = 'twixelwall'
client_id = 'YOURCLIENTID'
secret = 'YOURSECRET'
token_filepath = '.twitchauthtoken.json'

[twixelbox]
window_resolution = 1080
cube_size = 500
img_filepath = 'twixelbox.png'
